### ISSUE TITLE
appimage not opening

### ISSUE THREAD

**Issue by test2a** [codext-remotecontrol/remotecontrol-desktop#10]
```
./Remotecontrol.Desktop-0.3.6.AppImage 
Checking for update
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
Update for version 0.3.6 is not available (latest version: 0.3.1, downgrade is disallowed).
[80863:0714/235955.620568:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
Segmentation fault

```

and 

```
./Remotecontrol.Desktop-0.3.5.AppImage 
Checking for update
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
Update for version 0.3.5 is not available (latest version: 0.3.1, downgrade is disallowed).
[81304:0715/000246.844198:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
Segmentation fault

```

**Comment by test2a** [comment]
both versions dont work

**Comment by danielehrhardt** [comment]
What system do you use?

**Comment by test2a** [comment]
@danielehrhardt 

```
Operating System: KDE neon 5.27
KDE Plasma Version: 5.27.6
KDE Frameworks Version: 5.108.0
Qt Version: 5.15.10
Kernel Version: 5.19.0-46-generic (64-bit)
Graphics Platform: Wayland
Processors: 4 × AMD Ryzen 3 3200U with Radeon Vega Mobile Gfx
Memory: 5.7 GiB of RAM
Graphics Processor: AMD Radeon Vega 3 Graphics
Manufacturer: LENOVO
Product Name: 81UT
System Version: Lenovo IdeaPad S145-15API
```

**Comment by danielehrhardt** [comment]
I tested on Ubuntu after i installed `sudo apt install libfuse2` it worked, maybe it is related to your Display Drivers or something similar. Currently there is nothing i can do here.

**Comment by danielehrhardt** [comment]
I tested on Ubuntu after i installed `sudo apt install libfuse2` it worked, maybe it is related to your Display Drivers or something similar. Currently there is nothing i can do here.

**Comment by test2a** [comment]
@danielehrhardt ok. i found the issue. x11 is working. that is working for you too.

check wayland. wayland does not work. maybe this is a library issue

**Comment by danielehrhardt** [comment]
> @danielehrhardt ok. i found the issue. x11 is working. that is working for you too.
> 
> check wayland. wayland does not work. maybe this is a library issue

wdym with Wayland?

**Comment by test2a** [comment]
@danielehrhardt https://www.maketecheasier.com/what-is-wayland/
https://www.howtogeek.com/900698/what-is-wayland-on-linux-and-how-is-it-different-from-x/

check your linux instance. it might have wayland. that will help you fix bugs because wayland is going to be default in the coming years now and x11 will be for old stuff
