### ISSUE TITLE
language

### ISSUE THREAD

**Issue by test2a** [codext-remotecontrol/remotecontrol-desktop#11]
The app is in german. it would be great if you have l10n keys so that english and other languages can be used depending on the locale of the computers

**Comment by test2a** [comment]
okay... i found the setting in the gear icon but not all labels are translated into english. i will do one thing, i will try to fix some and submit a PR

**Comment by danielehrhardt** [comment]
> okay... i found the setting in the gear icon but not all labels are translated into english. i will do one thing, i will try to fix some and submit a PR

nice! Sounds good to me. 
We also can make English default or add some Language detection.

**Comment by test2a** [comment]
@danielehrhardt i have submitted a PR. i have tried to just copy from other labels, maybe this isnt a good way.
