### ISSUE TITLE
create your own turn server

### ISSUE THREAD

**Issue by BadSchock** [codext-remotecontrol/remotecontrol-desktop#22]
I'm trying my best to create and use my own server but the program simply won't connect when I try to do it like this:
`export const AppConfig = {
    production: true,
    environment: 'WEB',
    appName: 'remotecontrol-desktop',
    api: 'turn:relay1.expressturn.com:3478',
};`

For example, it returns the url to me

http://turn/socket.io/?EIO=4&transport=polling&t=OtwNZpA
and it doesn't work. I tried changing the method in the socket.service.ts file
the first method is the old one and the second one is the new one:

`this.socket = io(AppConfig.api, {
            reconnection: true,
            reconnectionDelay: 1000,
        });
    }`
    
   `this.socket = io('turns://relay1.expressturn.com:3478', {
    reconnection: true,
    reconnectionDelay: 1000,
    transports: ['websocket'], // Use apenas WebSockets para a comunicação
});`

but it didn't work either, but when I enter the default url of the file it works. I created my own server and then created a test on the website https://www.expressturn.com
But none of them worked, can anyone help me?

**Comment by danielehrhardt** [comment]
Deploy this to some node Server:
https://github.com/codext-remotecontrol/remotecontrol-desktop/tree/main/socketio-node

turn servers you can adjust here:
https://github.com/codext-remotecontrol/remotecontrol-desktop/blob/d07d73bfcfef891540b21ea8363c088c2ac2d25c/src/pages/remote/remote.page.ts#L337
