### ISSUE TITLE
 I tried to implement another server to manage the connections, but I couldn't switch

### ISSUE THREAD

**Issue by BadSchock** [codext-remotecontrol/remotecontrol-desktop#24]
I tried to follow the step of changing the turn server

turn servers you can adjust here:
[remotecontrol-desktop/src/pages/remote/remote.page.ts](https://github.com/codext-remotecontrol/remotecontrol-desktop/blob/d07d73bfcfef891540b21ea8363c088c2ac2d25c/src/pages/remote/remote.page.ts#L337)

Line 337 in [d07d73b](https://github.com/codext-remotecontrol/remotecontrol-desktop/commit/d07d73bfcfef891540b21ea8363c088c2ac2d25c)

 'turn:turn.codext.de:80?transport=tcp',
 
 But I couldn't do it, I don't think it's possible to actually change the server, would anyone have a manual? I already have a machine with the coturn installed and running.

**Comment by danielehrhardt** [comment]
You need to host this NodeJS Script:
https://github.com/codext-remotecontrol/remotecontrol-desktop/tree/main/socketio-node

and then you can modify the enviroment file here:
https://github.com/codext-remotecontrol/remotecontrol-desktop/blob/main/src/environments/environment.ts

**Comment by BadSchock** [comment]
it worket out. Thanks!!
